/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessages_Logic1 = require('./code/customermessages-logic1');
const customermessages_Logic2 = require('./code/customermessages-logic2');
const customermessages_Action1_Logic = require('./code/customermessages-action1-logic');

class productSupportSrv extends LCAPApplicationService {
    async init() {

        this.after('READ', 'CustomerMessages', async (results, request) => {
            await customermessages_Logic1(results, request);
        });

        this.on(['CREATE', 'DELETE', 'UPDATE'], 'CustomerMessages', async (request, next) => {
            await customermessages_Logic2(request);
            return next();
        });

        this.on('Action1', 'CustomerMessages', async (request, next) => {
            await customermessages_Action1_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    productSupportSrv
};